hugover: extended_0.115.2
serve:
  - key: default
    config: config.yml
build:
  - key: default
    config: config.yml
menu:
  - key: content
    title: Content
    menuItems:
       - key: homepage
       - key: blog_items

  - key: assets
    title: Assets
    menuItems:
       - key: images

  - key: settings
    title: Settings
    menuItems:
       - key: mainConfig

singles:

  - key: images
    title: Images
    hidePreviewIcon: true
    hideExternalEditIcon: true
    hideSaveButton: true
    file: static/.pogo-images-paragraph.md
    fields:
      - key: image
        type: bundle-manager
        path: "/static/images/"
        extensions:
          - svg
          - png
          - jpg
          - gif
        fields:
          - key: thumb
            title: Thumb
            type: bundle-image-thumbnail

  - key: mainConfig
    title: Site Configuration
    file: config.yml
    fields:
      - key: title
        title: Site Title
        type: string
        tip: Your page title.
      - key: baseURL
        title: Base URL
        type: string
        tip: Your site URL.

      - key: params
        type: pull
        fields:

        - key: Name
          type: string
          title: Header Title

        - key: Date
          type: string

        - key: menu
          title: Menu
          type: accordion
          fields:

            - key: disabled
              type: boolean

            - key: title
              title: Title
              type: string
              arrayTitle: true

            - key: url
              type: string

        - key: FooterText
          type: markdown

  - key: homepage
    file: /content/_index.md
    previewUrl: /
    title: Homepage
    _mergePartial: composit_page
    fields:
      - key: description
        type: hidden
      - key: mainContentInfo
        type: hidden
      - key: mainContent
        type: hidden
      - key: content_blocks_below_main
        type: hidden


